#cloud-config

system_info:
  default_user:
    name: packer
    groups: sudo
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash

password: packer
ssh_pwauth: True
chpasswd: { expire: False }

package_update: true
package_upgrade: false
packages:
  - qemu-guest-agent

runcmd:
  - ["sudo", "systemctl", "enable", "--now", "qemu-guest-agent"]

power_state:
  mode: reboot
  message: Rebooting after package installation.