// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package oci

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName     *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType   *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion   *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug         *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce         *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError       *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars      map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	Image               *string           `mapstructure:"image" cty:"image" hcl:"image"`
	ServiceAccountName  *string           `mapstructure:"service_account_name" required:"false" cty:"service_account_name" hcl:"service_account_name"`
	RegistryUsername    *string           `mapstructure:"registry_username" required:"false" cty:"registry_username" hcl:"registry_username"`
	RegistryPassword    *string           `mapstructure:"registry_password" required:"false" cty:"registry_password" hcl:"registry_password"`
	RegistrySecretName  *string           `mapstructure:"registry_secret_name" required:"false" cty:"registry_secret_name" hcl:"registry_secret_name"`
	RegistryInsecure    *bool             `mapstructure:"registry_insecure" required:"false" cty:"registry_insecure" hcl:"registry_insecure"`
	UploadTimeOut       *string           `mapstructure:"upload_timeout" required:"false" cty:"upload_timeout" hcl:"upload_timeout"`
	KeepExport          *bool             `mapstructure:"keep_export" required:"false" cty:"keep_export" hcl:"keep_export"`
	ImageFormat         *string           `mapstructure:"image_format" required:"false" cty:"image_format" hcl:"image_format"`
	DefaultPreference   *string           `mapstructure:"default_preference" required:"false" cty:"default_preference" hcl:"default_preference"`
	DefaultInstanceType *string           `mapstructure:"default_instance_type" required:"false" cty:"default_instance_type" hcl:"default_instance_type"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"image":                      &hcldec.AttrSpec{Name: "image", Type: cty.String, Required: false},
		"service_account_name":       &hcldec.AttrSpec{Name: "service_account_name", Type: cty.String, Required: false},
		"registry_username":          &hcldec.AttrSpec{Name: "registry_username", Type: cty.String, Required: false},
		"registry_password":          &hcldec.AttrSpec{Name: "registry_password", Type: cty.String, Required: false},
		"registry_secret_name":       &hcldec.AttrSpec{Name: "registry_secret_name", Type: cty.String, Required: false},
		"registry_insecure":          &hcldec.AttrSpec{Name: "registry_insecure", Type: cty.Bool, Required: false},
		"upload_timeout":             &hcldec.AttrSpec{Name: "upload_timeout", Type: cty.String, Required: false},
		"keep_export":                &hcldec.AttrSpec{Name: "keep_export", Type: cty.Bool, Required: false},
		"image_format":               &hcldec.AttrSpec{Name: "image_format", Type: cty.String, Required: false},
		"default_preference":         &hcldec.AttrSpec{Name: "default_preference", Type: cty.String, Required: false},
		"default_instance_type":      &hcldec.AttrSpec{Name: "default_instance_type", Type: cty.String, Required: false},
	}
	return s
}
