name: Notify Integration Release (Tag)
on:
  push:
    tags:
      - '*.*.*'   # Proper releases

jobs:
  strip-version:
    runs-on: ubuntu-latest
    outputs:
      packer-version: ${{ steps.strip.outputs.packer-version }}
    steps:
      - name: Strip leading v from version tag
        id: strip
        env:
          REF: ${{ github.ref_name }}
        run: |
          echo "packer-version=$(echo "$REF" | sed -E 's/v?([0-9]+\.[0-9]+\.[0-9]+)/\1/')" >> "$GITHUB_OUTPUT"

  notify-release:
    needs:
      - strip-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      # Ensure that Docs are Compiled
      - uses: actions/setup-go@v5
      - shell: bash
        run: make generate
      - shell: bash
        run: |
          if [[ -z "$(git status -s)" ]]; then
            echo "OK"
          else
            echo "Docs have been updated, but the compiled docs have not been committed."
            echo "Run 'make generate', and commit the result to resolve this error."
            exit 1
          fi

      # Perform the Release
      - name: Checkout integration-release-action
        uses: actions/checkout@v4
        with:
          repository: hashicorp/integration-release-action
          path: ./integration-release-action
      - name: Notify Release
        # disable release to https://developer.hashicorp.com/packer/integrations until an identifier is assigned.
        if: false
        uses: ./integration-release-action
        with:
          # The Packer team will use the integration identifier to register the integration;
          # the expected format is packer/<GitHub Org Name>/<plugin-name>
          integration_identifier: "packer/pelotech/kubevirt"
          release_version: ${{ needs.strip-version.outputs.packer-version }}
          release_sha: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
