name: pre-commit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - name: tools setup
        uses: jdx/mise-action@v5
      - name: pre-commit
        run: prek run --all-files --show-diff-on-failure
