# This is a manually triggered action workflow.
# It uses Packer at latest version to init, validate and build
# an example configuration in a folder.
name: test plugin

on:
  push:

env:
  PRODUCT_VERSION: "1.10.3"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ./example/build.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./example/build.pkr.hcl"

      - name: Run `packer build`
        id: build
        run: "PACKER_LOG=1 packer build ./example/build.pkr.hcl"